# Copyright 2025 Dimitri Koshkin. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2

name: imgldr
type: application
description: A Helm chart for Imgldr

home: https://github.com/dkoshkin/imgldr
maintainers:
- name: dkoshkin
  email: dimitri.koshkin@gmail.com
sources:
- https://github.com/dkoshkin

appVersion: v0.0.0-dev
version: v0.0.0-dev
