# Copyright 2025 Dimitri Koshkin. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    labels:
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: imgldr
    name: imgldr-leader-election-rolebinding
    namespace: {{ .Release.Namespace }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: imgldr-leader-election-role
subjects:
    - kind: ServiceAccount
      name: imgldr-controller-manager
      namespace: {{ .Release.Namespace }}
