# Copyright 2025 Dimitri Koshkin. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2

name: golang-repository-template
type: application
description: A Helm chart for Golang Repository Template

home: https://github.com/dkoshkin/golang-repository-template
maintainers:
- name: dkoshkin
  email: dimitri.koshkin@gmail.com
sources:
- https://github.com/dkoshkin

appVersion: v0.0.0-dev
version: v0.0.0-dev
