# Copyright 2025 Dimitri Koshkin. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    labels:
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: golang-repository-template
    name: golang-repository-template-leader-election-rolebinding
    namespace: {{ .Release.Namespace }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: golang-repository-template-leader-election-role
subjects:
    - kind: ServiceAccount
      name: golang-repository-template-controller-manager
      namespace: {{ .Release.Namespace }}
