# Copyright 2025 Dimitri Koshkin. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    labels:
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: golang-repository-template
    name: golang-repository-template-manager-rolebinding
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: golang-repository-template-manager-role
subjects:
    - kind: ServiceAccount
      name: golang-repository-template-controller-manager
      namespace: {{ .Release.Namespace }}
