# Copyright 2025 Dimitri Koshkin. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.metrics.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: golang-repository-template-metrics-auth-rolebinding
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: golang-repository-template-metrics-auth-role
subjects:
    - kind: ServiceAccount
      name: golang-repository-template-controller-manager
      namespace: {{ .Release.Namespace }}
{{- end }}
